/**
 * @file feb_can_lib.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Sun Mar  2 21:34:33 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef FEB_CAN_LIB_H
#define FEB_CAN_LIB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FEB_CAN_LIB_PINGPONG_FRAME_ID (0x00u)

/* Frame lengths in bytes. */
#define FEB_CAN_LIB_PINGPONG_LENGTH (2u)

/* Extended or standard frame types. */
#define FEB_CAN_LIB_PINGPONG_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define FEB_CAN_LIB_PINGPONG_NAME "pingpong"

/* Signal Names. */
#define FEB_CAN_LIB_PINGPONG_COUNT_NAME "count"

/**
 * Signals in message pingpong.
 *
 * All signal values are as on the CAN bus.
 */
struct feb_can_lib_pingpong_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t count;
};

/**
 * Pack message pingpong.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int feb_can_lib_pingpong_pack(
    uint8_t *dst_p,
    const struct feb_can_lib_pingpong_t *src_p,
    size_t size);

/**
 * Unpack message pingpong.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int feb_can_lib_pingpong_unpack(
    struct feb_can_lib_pingpong_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from pingpong.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int feb_can_lib_pingpong_init(struct feb_can_lib_pingpong_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t feb_can_lib_pingpong_count_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double feb_can_lib_pingpong_count_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool feb_can_lib_pingpong_count_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
